// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: mvp.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const cancelAppointment = `-- name: CancelAppointment :one
UPDATE appointments
SET status = 'cancelled', updated_at = now()
WHERE id = $1
RETURNING id, tenant_id, customer_id, provider_id, service_id, slot_id, start_at, end_at, status, notes, created_at, updated_at
`

func (q *Queries) CancelAppointment(ctx context.Context, id uuid.UUID) (Appointment, error) {
	row := q.db.QueryRow(ctx, cancelAppointment, id)
	var i Appointment
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CustomerID,
		&i.ProviderID,
		&i.ServiceID,
		&i.SlotID,
		&i.StartAt,
		&i.EndAt,
		&i.Status,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const countAppointments = `-- name: CountAppointments :one
SELECT count(*) FROM appointments
WHERE tenant_id = $1
  AND ($2::uuid IS NULL OR provider_id = $2)
  AND ($3::uuid IS NULL OR customer_id = $3)
  AND ($4::text = '' OR status = $4)
`

type CountAppointmentsParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	Column2  uuid.UUID `json:"column_2"`
	Column3  uuid.UUID `json:"column_3"`
	Column4  string    `json:"column_4"`
}

func (q *Queries) CountAppointments(ctx context.Context, arg CountAppointmentsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAppointments,
		arg.TenantID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countCustomers = `-- name: CountCustomers :one
SELECT count(*) FROM customers
WHERE tenant_id = $1
  AND ($2::text = '' OR coalesce(first_name, '') ILIKE '%' || $2 || '%' OR coalesce(last_name, '') ILIKE '%' || $2 || '%')
`

type CountCustomersParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	Column2  string    `json:"column_2"`
}

func (q *Queries) CountCustomers(ctx context.Context, arg CountCustomersParams) (int64, error) {
	row := q.db.QueryRow(ctx, countCustomers, arg.TenantID, arg.Column2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countProviders = `-- name: CountProviders :one
SELECT count(*) FROM providers
WHERE tenant_id = $1
  AND ($2::text = '' OR name ILIKE '%' || $2 || '%')
  AND ($3::boolean IS NULL OR active = $3)
`

type CountProvidersParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	Column2  string    `json:"column_2"`
	Column3  bool      `json:"column_3"`
}

func (q *Queries) CountProviders(ctx context.Context, arg CountProvidersParams) (int64, error) {
	row := q.db.QueryRow(ctx, countProviders, arg.TenantID, arg.Column2, arg.Column3)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countServices = `-- name: CountServices :one
SELECT count(*) FROM services
WHERE tenant_id = $1
  AND ($2::text = '' OR name ILIKE '%' || $2 || '%')
  AND ($3::boolean IS NULL OR active = $3)
`

type CountServicesParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	Column2  string    `json:"column_2"`
	Column3  bool      `json:"column_3"`
}

func (q *Queries) CountServices(ctx context.Context, arg CountServicesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countServices, arg.TenantID, arg.Column2, arg.Column3)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTenantChannels = `-- name: CountTenantChannels :one
SELECT count(*)
FROM tenant_channels
WHERE tenant_id = $1
  AND ($2::text = '' OR channel_type = $2)
  AND ($3::boolean IS NULL OR active = $3)
`

type CountTenantChannelsParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	Column2  string    `json:"column_2"`
	Column3  bool      `json:"column_3"`
}

func (q *Queries) CountTenantChannels(ctx context.Context, arg CountTenantChannelsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countTenantChannels, arg.TenantID, arg.Column2, arg.Column3)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTenants = `-- name: CountTenants :one
SELECT count(*) FROM tenants
WHERE ($1::text = '' OR name ILIKE '%' || $1 || '%')
  AND ($2::boolean IS NULL OR active = $2)
`

type CountTenantsParams struct {
	Column1 string `json:"column_1"`
	Column2 bool   `json:"column_2"`
}

func (q *Queries) CountTenants(ctx context.Context, arg CountTenantsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countTenants, arg.Column1, arg.Column2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAppointment = `-- name: CreateAppointment :one
INSERT INTO appointments (tenant_id, customer_id, provider_id, service_id, slot_id, start_at, end_at, status, notes)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, tenant_id, customer_id, provider_id, service_id, slot_id, start_at, end_at, status, notes, created_at, updated_at
`

type CreateAppointmentParams struct {
	TenantID   uuid.UUID     `json:"tenant_id"`
	CustomerID uuid.UUID     `json:"customer_id"`
	ProviderID uuid.UUID     `json:"provider_id"`
	ServiceID  uuid.UUID     `json:"service_id"`
	SlotID     uuid.NullUUID `json:"slot_id"`
	StartAt    time.Time     `json:"start_at"`
	EndAt      time.Time     `json:"end_at"`
	Status     string        `json:"status"`
	Notes      pgtype.Text   `json:"notes"`
}

func (q *Queries) CreateAppointment(ctx context.Context, arg CreateAppointmentParams) (Appointment, error) {
	row := q.db.QueryRow(ctx, createAppointment,
		arg.TenantID,
		arg.CustomerID,
		arg.ProviderID,
		arg.ServiceID,
		arg.SlotID,
		arg.StartAt,
		arg.EndAt,
		arg.Status,
		arg.Notes,
	)
	var i Appointment
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CustomerID,
		&i.ProviderID,
		&i.ServiceID,
		&i.SlotID,
		&i.StartAt,
		&i.EndAt,
		&i.Status,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createAppointmentEvent = `-- name: CreateAppointmentEvent :one
INSERT INTO appointment_events (appointment_id, event_type, payload)
VALUES ($1, $2, $3)
RETURNING id, appointment_id, event_type, payload, created_at
`

type CreateAppointmentEventParams struct {
	AppointmentID uuid.UUID `json:"appointment_id"`
	EventType     string    `json:"event_type"`
	Payload       []byte    `json:"payload"`
}

func (q *Queries) CreateAppointmentEvent(ctx context.Context, arg CreateAppointmentEventParams) (AppointmentEvent, error) {
	row := q.db.QueryRow(ctx, createAppointmentEvent, arg.AppointmentID, arg.EventType, arg.Payload)
	var i AppointmentEvent
	err := row.Scan(
		&i.ID,
		&i.AppointmentID,
		&i.EventType,
		&i.Payload,
		&i.CreatedAt,
	)
	return i, err
}

const createAppointmentSlot = `-- name: CreateAppointmentSlot :one
INSERT INTO appointment_slots (tenant_id, provider_id, start_at, end_at, status)
SELECT $1, $2, $3, $4, 'available'
WHERE NOT EXISTS (
  SELECT 1 FROM appointment_slots
  WHERE provider_id = $2 AND start_at = $3 AND end_at = $4
)
RETURNING id, tenant_id, provider_id, start_at, end_at, status, appointment_id, created_at
`

type CreateAppointmentSlotParams struct {
	TenantID   uuid.UUID `json:"tenant_id"`
	ProviderID uuid.UUID `json:"provider_id"`
	StartAt    time.Time `json:"start_at"`
	EndAt      time.Time `json:"end_at"`
}

func (q *Queries) CreateAppointmentSlot(ctx context.Context, arg CreateAppointmentSlotParams) (AppointmentSlot, error) {
	row := q.db.QueryRow(ctx, createAppointmentSlot,
		arg.TenantID,
		arg.ProviderID,
		arg.StartAt,
		arg.EndAt,
	)
	var i AppointmentSlot
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ProviderID,
		&i.StartAt,
		&i.EndAt,
		&i.Status,
		&i.AppointmentID,
		&i.CreatedAt,
	)
	return i, err
}

const createConversationMessage = `-- name: CreateConversationMessage :one
INSERT INTO conversation_messages (thread_id, direction, message, metadata)
VALUES ($1, $2, $3, $4)
RETURNING id, thread_id, direction, message, metadata, created_at
`

type CreateConversationMessageParams struct {
	ThreadID  uuid.UUID `json:"thread_id"`
	Direction string    `json:"direction"`
	Message   string    `json:"message"`
	Metadata  []byte    `json:"metadata"`
}

func (q *Queries) CreateConversationMessage(ctx context.Context, arg CreateConversationMessageParams) (ConversationMessage, error) {
	row := q.db.QueryRow(ctx, createConversationMessage,
		arg.ThreadID,
		arg.Direction,
		arg.Message,
		arg.Metadata,
	)
	var i ConversationMessage
	err := row.Scan(
		&i.ID,
		&i.ThreadID,
		&i.Direction,
		&i.Message,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const createConversationThread = `-- name: CreateConversationThread :one
INSERT INTO conversation_threads (tenant_id, customer_id)
VALUES ($1, $2)
RETURNING id, tenant_id, customer_id, created_at
`

type CreateConversationThreadParams struct {
	TenantID   uuid.UUID `json:"tenant_id"`
	CustomerID uuid.UUID `json:"customer_id"`
}

func (q *Queries) CreateConversationThread(ctx context.Context, arg CreateConversationThreadParams) (ConversationThread, error) {
	row := q.db.QueryRow(ctx, createConversationThread, arg.TenantID, arg.CustomerID)
	var i ConversationThread
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CustomerID,
		&i.CreatedAt,
	)
	return i, err
}

const createCustomer = `-- name: CreateCustomer :one
INSERT INTO customers (tenant_id, first_name, last_name, notes)
VALUES ($1, $2, $3, $4)
RETURNING id, tenant_id, first_name, last_name, notes, created_at, updated_at
`

type CreateCustomerParams struct {
	TenantID  uuid.UUID   `json:"tenant_id"`
	FirstName pgtype.Text `json:"first_name"`
	LastName  pgtype.Text `json:"last_name"`
	Notes     pgtype.Text `json:"notes"`
}

func (q *Queries) CreateCustomer(ctx context.Context, arg CreateCustomerParams) (Customer, error) {
	row := q.db.QueryRow(ctx, createCustomer,
		arg.TenantID,
		arg.FirstName,
		arg.LastName,
		arg.Notes,
	)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.FirstName,
		&i.LastName,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createCustomerChannel = `-- name: CreateCustomerChannel :one
INSERT INTO customer_channels (customer_id, tenant_channel_id, external_identifier)
VALUES ($1, $2, $3)
RETURNING id, customer_id, tenant_channel_id, external_identifier, created_at
`

type CreateCustomerChannelParams struct {
	CustomerID         uuid.UUID `json:"customer_id"`
	TenantChannelID    uuid.UUID `json:"tenant_channel_id"`
	ExternalIdentifier string    `json:"external_identifier"`
}

func (q *Queries) CreateCustomerChannel(ctx context.Context, arg CreateCustomerChannelParams) (CustomerChannel, error) {
	row := q.db.QueryRow(ctx, createCustomerChannel, arg.CustomerID, arg.TenantChannelID, arg.ExternalIdentifier)
	var i CustomerChannel
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.TenantChannelID,
		&i.ExternalIdentifier,
		&i.CreatedAt,
	)
	return i, err
}

const createEvolutionWebhookLog = `-- name: CreateEvolutionWebhookLog :one
INSERT INTO webhook_logs (tenant_id, source, payload, tenant_channel_id, evolution_message_id)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (tenant_channel_id, evolution_message_id)
WHERE tenant_channel_id IS NOT NULL AND evolution_message_id IS NOT NULL
DO NOTHING
RETURNING id, tenant_id, source, payload, created_at, tenant_channel_id, evolution_message_id
`

type CreateEvolutionWebhookLogParams struct {
	TenantID           uuid.NullUUID `json:"tenant_id"`
	Source             string        `json:"source"`
	Payload            []byte        `json:"payload"`
	TenantChannelID    pgtype.UUID   `json:"tenant_channel_id"`
	EvolutionMessageID pgtype.Text   `json:"evolution_message_id"`
}

func (q *Queries) CreateEvolutionWebhookLog(ctx context.Context, arg CreateEvolutionWebhookLogParams) (WebhookLog, error) {
	row := q.db.QueryRow(ctx, createEvolutionWebhookLog,
		arg.TenantID,
		arg.Source,
		arg.Payload,
		arg.TenantChannelID,
		arg.EvolutionMessageID,
	)
	var i WebhookLog
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Source,
		&i.Payload,
		&i.CreatedAt,
		&i.TenantChannelID,
		&i.EvolutionMessageID,
	)
	return i, err
}

const createProvider = `-- name: CreateProvider :one
INSERT INTO providers (tenant_id, name)
VALUES ($1, $2)
RETURNING id, tenant_id, name, active, created_at, updated_at
`

type CreateProviderParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	Name     string    `json:"name"`
}

func (q *Queries) CreateProvider(ctx context.Context, arg CreateProviderParams) (Provider, error) {
	row := q.db.QueryRow(ctx, createProvider, arg.TenantID, arg.Name)
	var i Provider
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createProviderAvailability = `-- name: CreateProviderAvailability :one
INSERT INTO provider_availability (provider_id, weekday, start_time, end_time)
VALUES ($1, $2, $3, $4)
RETURNING id, provider_id, weekday, start_time, end_time
`

type CreateProviderAvailabilityParams struct {
	ProviderID uuid.UUID `json:"provider_id"`
	Weekday    int16     `json:"weekday"`
	StartTime  string    `json:"start_time"`
	EndTime    string    `json:"end_time"`
}

func (q *Queries) CreateProviderAvailability(ctx context.Context, arg CreateProviderAvailabilityParams) (ProviderAvailability, error) {
	row := q.db.QueryRow(ctx, createProviderAvailability,
		arg.ProviderID,
		arg.Weekday,
		arg.StartTime,
		arg.EndTime,
	)
	var i ProviderAvailability
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.Weekday,
		&i.StartTime,
		&i.EndTime,
	)
	return i, err
}

const createProviderException = `-- name: CreateProviderException :one
INSERT INTO provider_exceptions (provider_id, start_at, end_at, reason)
VALUES ($1, $2, $3, $4)
RETURNING id, provider_id, start_at, end_at, reason, created_at
`

type CreateProviderExceptionParams struct {
	ProviderID uuid.UUID   `json:"provider_id"`
	StartAt    time.Time   `json:"start_at"`
	EndAt      time.Time   `json:"end_at"`
	Reason     pgtype.Text `json:"reason"`
}

func (q *Queries) CreateProviderException(ctx context.Context, arg CreateProviderExceptionParams) (ProviderException, error) {
	row := q.db.QueryRow(ctx, createProviderException,
		arg.ProviderID,
		arg.StartAt,
		arg.EndAt,
		arg.Reason,
	)
	var i ProviderException
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.StartAt,
		&i.EndAt,
		&i.Reason,
		&i.CreatedAt,
	)
	return i, err
}

const createService = `-- name: CreateService :one
INSERT INTO services (tenant_id, name, duration_minutes)
VALUES ($1, $2, $3)
RETURNING id, tenant_id, name, duration_minutes, active, created_at, updated_at
`

type CreateServiceParams struct {
	TenantID        uuid.UUID `json:"tenant_id"`
	Name            string    `json:"name"`
	DurationMinutes int32     `json:"duration_minutes"`
}

func (q *Queries) CreateService(ctx context.Context, arg CreateServiceParams) (Service, error) {
	row := q.db.QueryRow(ctx, createService, arg.TenantID, arg.Name, arg.DurationMinutes)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.DurationMinutes,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTenant = `-- name: CreateTenant :one
INSERT INTO tenants (name, timezone, greeting_message)
VALUES ($1, $2, COALESCE($3, '¡Hola! ¿Dime en qué puedo ayudarte?'))
RETURNING id, name, timezone, active, greeting_message, created_at, updated_at
`

type CreateTenantParams struct {
	Name     string      `json:"name"`
	Timezone string      `json:"timezone"`
	Column3  interface{} `json:"column_3"`
}

type CreateTenantRow struct {
	ID              uuid.UUID `json:"id"`
	Name            string    `json:"name"`
	Timezone        string    `json:"timezone"`
	Active          bool      `json:"active"`
	GreetingMessage string    `json:"greeting_message"`
	CreatedAt       time.Time `json:"created_at"`
	UpdatedAt       time.Time `json:"updated_at"`
}

func (q *Queries) CreateTenant(ctx context.Context, arg CreateTenantParams) (CreateTenantRow, error) {
	row := q.db.QueryRow(ctx, createTenant, arg.Name, arg.Timezone, arg.Column3)
	var i CreateTenantRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Timezone,
		&i.Active,
		&i.GreetingMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTenantChannel = `-- name: CreateTenantChannel :one
INSERT INTO tenant_channels (tenant_id, channel_type, external_id, external_key)
VALUES ($1, $2, $3, $4)
RETURNING id, tenant_id, channel_type, external_id, external_key, active, created_at
`

type CreateTenantChannelParams struct {
	TenantID    uuid.UUID   `json:"tenant_id"`
	ChannelType string      `json:"channel_type"`
	ExternalID  string      `json:"external_id"`
	ExternalKey pgtype.Text `json:"external_key"`
}

func (q *Queries) CreateTenantChannel(ctx context.Context, arg CreateTenantChannelParams) (TenantChannel, error) {
	row := q.db.QueryRow(ctx, createTenantChannel,
		arg.TenantID,
		arg.ChannelType,
		arg.ExternalID,
		arg.ExternalKey,
	)
	var i TenantChannel
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ChannelType,
		&i.ExternalID,
		&i.ExternalKey,
		&i.Active,
		&i.CreatedAt,
	)
	return i, err
}

const createWebhookLog = `-- name: CreateWebhookLog :one
INSERT INTO webhook_logs (tenant_id, source, payload)
VALUES ($1, $2, $3)
RETURNING id, tenant_id, source, payload, created_at
`

type CreateWebhookLogParams struct {
	TenantID uuid.NullUUID `json:"tenant_id"`
	Source   string        `json:"source"`
	Payload  []byte        `json:"payload"`
}

type CreateWebhookLogRow struct {
	ID        uuid.UUID     `json:"id"`
	TenantID  uuid.NullUUID `json:"tenant_id"`
	Source    string        `json:"source"`
	Payload   []byte        `json:"payload"`
	CreatedAt time.Time     `json:"created_at"`
}

func (q *Queries) CreateWebhookLog(ctx context.Context, arg CreateWebhookLogParams) (CreateWebhookLogRow, error) {
	row := q.db.QueryRow(ctx, createWebhookLog, arg.TenantID, arg.Source, arg.Payload)
	var i CreateWebhookLogRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Source,
		&i.Payload,
		&i.CreatedAt,
	)
	return i, err
}

const deactivateProvider = `-- name: DeactivateProvider :one
UPDATE providers
SET active = false, updated_at = now()
WHERE id = $1
RETURNING id, tenant_id, name, active, created_at, updated_at
`

func (q *Queries) DeactivateProvider(ctx context.Context, id uuid.UUID) (Provider, error) {
	row := q.db.QueryRow(ctx, deactivateProvider, id)
	var i Provider
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deactivateService = `-- name: DeactivateService :one
UPDATE services
SET active = false, updated_at = now()
WHERE id = $1
RETURNING id, tenant_id, name, duration_minutes, active, created_at, updated_at
`

func (q *Queries) DeactivateService(ctx context.Context, id uuid.UUID) (Service, error) {
	row := q.db.QueryRow(ctx, deactivateService, id)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.DurationMinutes,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deactivateTenant = `-- name: DeactivateTenant :one
UPDATE tenants
SET active = false, updated_at = now()
WHERE id = $1
RETURNING id, name, timezone, active, greeting_message, created_at, updated_at
`

type DeactivateTenantRow struct {
	ID              uuid.UUID `json:"id"`
	Name            string    `json:"name"`
	Timezone        string    `json:"timezone"`
	Active          bool      `json:"active"`
	GreetingMessage string    `json:"greeting_message"`
	CreatedAt       time.Time `json:"created_at"`
	UpdatedAt       time.Time `json:"updated_at"`
}

func (q *Queries) DeactivateTenant(ctx context.Context, id uuid.UUID) (DeactivateTenantRow, error) {
	row := q.db.QueryRow(ctx, deactivateTenant, id)
	var i DeactivateTenantRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Timezone,
		&i.Active,
		&i.GreetingMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deactivateTenantChannel = `-- name: DeactivateTenantChannel :one
UPDATE tenant_channels
SET active = false
WHERE id = $1
RETURNING id, tenant_id, channel_type, external_id, external_key, active, created_at
`

func (q *Queries) DeactivateTenantChannel(ctx context.Context, id uuid.UUID) (TenantChannel, error) {
	row := q.db.QueryRow(ctx, deactivateTenantChannel, id)
	var i TenantChannel
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ChannelType,
		&i.ExternalID,
		&i.ExternalKey,
		&i.Active,
		&i.CreatedAt,
	)
	return i, err
}

const getAppointment = `-- name: GetAppointment :one
SELECT id, tenant_id, customer_id, provider_id, service_id, slot_id, start_at, end_at, status, notes, created_at, updated_at
FROM appointments
WHERE id = $1
`

func (q *Queries) GetAppointment(ctx context.Context, id uuid.UUID) (Appointment, error) {
	row := q.db.QueryRow(ctx, getAppointment, id)
	var i Appointment
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CustomerID,
		&i.ProviderID,
		&i.ServiceID,
		&i.SlotID,
		&i.StartAt,
		&i.EndAt,
		&i.Status,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAppointmentSlotForUpdate = `-- name: GetAppointmentSlotForUpdate :one
SELECT id, tenant_id, provider_id, start_at, end_at, status, appointment_id, created_at
FROM appointment_slots
WHERE id = $1
FOR UPDATE
`

func (q *Queries) GetAppointmentSlotForUpdate(ctx context.Context, id uuid.UUID) (AppointmentSlot, error) {
	row := q.db.QueryRow(ctx, getAppointmentSlotForUpdate, id)
	var i AppointmentSlot
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ProviderID,
		&i.StartAt,
		&i.EndAt,
		&i.Status,
		&i.AppointmentID,
		&i.CreatedAt,
	)
	return i, err
}

const getConversationState = `-- name: GetConversationState :one
SELECT id, tenant_id, customer_id, state, data, updated_at
FROM conversation_state
WHERE tenant_id = $1 AND customer_id = $2
`

type GetConversationStateParams struct {
	TenantID   uuid.UUID `json:"tenant_id"`
	CustomerID uuid.UUID `json:"customer_id"`
}

func (q *Queries) GetConversationState(ctx context.Context, arg GetConversationStateParams) (ConversationState, error) {
	row := q.db.QueryRow(ctx, getConversationState, arg.TenantID, arg.CustomerID)
	var i ConversationState
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CustomerID,
		&i.State,
		&i.Data,
		&i.UpdatedAt,
	)
	return i, err
}

const getConversationThread = `-- name: GetConversationThread :one
SELECT id, tenant_id, customer_id, created_at
FROM conversation_threads
WHERE id = $1
`

func (q *Queries) GetConversationThread(ctx context.Context, id uuid.UUID) (ConversationThread, error) {
	row := q.db.QueryRow(ctx, getConversationThread, id)
	var i ConversationThread
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CustomerID,
		&i.CreatedAt,
	)
	return i, err
}

const getConversationThreadByCustomer = `-- name: GetConversationThreadByCustomer :one
SELECT id, tenant_id, customer_id, created_at
FROM conversation_threads
WHERE tenant_id = $1 AND customer_id = $2
ORDER BY created_at DESC
LIMIT 1
`

type GetConversationThreadByCustomerParams struct {
	TenantID   uuid.UUID `json:"tenant_id"`
	CustomerID uuid.UUID `json:"customer_id"`
}

func (q *Queries) GetConversationThreadByCustomer(ctx context.Context, arg GetConversationThreadByCustomerParams) (ConversationThread, error) {
	row := q.db.QueryRow(ctx, getConversationThreadByCustomer, arg.TenantID, arg.CustomerID)
	var i ConversationThread
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CustomerID,
		&i.CreatedAt,
	)
	return i, err
}

const getCustomer = `-- name: GetCustomer :one
SELECT id, tenant_id, first_name, last_name, notes, created_at, updated_at
FROM customers
WHERE id = $1
`

func (q *Queries) GetCustomer(ctx context.Context, id uuid.UUID) (Customer, error) {
	row := q.db.QueryRow(ctx, getCustomer, id)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.FirstName,
		&i.LastName,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCustomerByChannel = `-- name: GetCustomerByChannel :one
SELECT c.id, c.tenant_id, c.first_name, c.last_name, c.notes, c.created_at, c.updated_at
FROM customers c
JOIN customer_channels cc ON cc.customer_id = c.id
WHERE cc.tenant_channel_id = $1 AND cc.external_identifier = $2
`

type GetCustomerByChannelParams struct {
	TenantChannelID    uuid.UUID `json:"tenant_channel_id"`
	ExternalIdentifier string    `json:"external_identifier"`
}

func (q *Queries) GetCustomerByChannel(ctx context.Context, arg GetCustomerByChannelParams) (Customer, error) {
	row := q.db.QueryRow(ctx, getCustomerByChannel, arg.TenantChannelID, arg.ExternalIdentifier)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.FirstName,
		&i.LastName,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProvider = `-- name: GetProvider :one
SELECT id, tenant_id, name, active, created_at, updated_at
FROM providers
WHERE id = $1
`

func (q *Queries) GetProvider(ctx context.Context, id uuid.UUID) (Provider, error) {
	row := q.db.QueryRow(ctx, getProvider, id)
	var i Provider
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getService = `-- name: GetService :one
SELECT id, tenant_id, name, duration_minutes, active, created_at, updated_at
FROM services
WHERE id = $1
`

func (q *Queries) GetService(ctx context.Context, id uuid.UUID) (Service, error) {
	row := q.db.QueryRow(ctx, getService, id)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.DurationMinutes,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTenant = `-- name: GetTenant :one
SELECT id, name, timezone, active, greeting_message, created_at, updated_at
FROM tenants
WHERE id = $1
`

type GetTenantRow struct {
	ID              uuid.UUID `json:"id"`
	Name            string    `json:"name"`
	Timezone        string    `json:"timezone"`
	Active          bool      `json:"active"`
	GreetingMessage string    `json:"greeting_message"`
	CreatedAt       time.Time `json:"created_at"`
	UpdatedAt       time.Time `json:"updated_at"`
}

func (q *Queries) GetTenant(ctx context.Context, id uuid.UUID) (GetTenantRow, error) {
	row := q.db.QueryRow(ctx, getTenant, id)
	var i GetTenantRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Timezone,
		&i.Active,
		&i.GreetingMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTenantChannel = `-- name: GetTenantChannel :one
SELECT id, tenant_id, channel_type, external_id, external_key, active, created_at
FROM tenant_channels
WHERE id = $1
`

func (q *Queries) GetTenantChannel(ctx context.Context, id uuid.UUID) (TenantChannel, error) {
	row := q.db.QueryRow(ctx, getTenantChannel, id)
	var i TenantChannel
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ChannelType,
		&i.ExternalID,
		&i.ExternalKey,
		&i.Active,
		&i.CreatedAt,
	)
	return i, err
}

const getTenantChannelByExternalID = `-- name: GetTenantChannelByExternalID :one
SELECT id, tenant_id, channel_type, external_id, external_key, active, created_at
FROM tenant_channels
WHERE external_id = $1 AND active = true
`

func (q *Queries) GetTenantChannelByExternalID(ctx context.Context, externalID string) (TenantChannel, error) {
	row := q.db.QueryRow(ctx, getTenantChannelByExternalID, externalID)
	var i TenantChannel
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ChannelType,
		&i.ExternalID,
		&i.ExternalKey,
		&i.Active,
		&i.CreatedAt,
	)
	return i, err
}

const listAppointments = `-- name: ListAppointments :many
SELECT id, tenant_id, customer_id, provider_id, service_id, slot_id, start_at, end_at, status, notes, created_at, updated_at
FROM appointments
WHERE tenant_id = $1
  AND ($2::uuid IS NULL OR provider_id = $2)
  AND ($3::uuid IS NULL OR customer_id = $3)
  AND ($4::text = '' OR status = $4)
ORDER BY start_at DESC
LIMIT $5 OFFSET $6
`

type ListAppointmentsParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	Column2  uuid.UUID `json:"column_2"`
	Column3  uuid.UUID `json:"column_3"`
	Column4  string    `json:"column_4"`
	Limit    int32     `json:"limit"`
	Offset   int32     `json:"offset"`
}

func (q *Queries) ListAppointments(ctx context.Context, arg ListAppointmentsParams) ([]Appointment, error) {
	rows, err := q.db.Query(ctx, listAppointments,
		arg.TenantID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Appointment{}
	for rows.Next() {
		var i Appointment
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.CustomerID,
			&i.ProviderID,
			&i.ServiceID,
			&i.SlotID,
			&i.StartAt,
			&i.EndAt,
			&i.Status,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAvailableSlots = `-- name: ListAvailableSlots :many
SELECT s.id, s.tenant_id, s.provider_id, s.start_at, s.end_at, s.status, s.appointment_id, s.created_at
FROM appointment_slots s
WHERE s.tenant_id = $1
  AND ($2::uuid IS NULL OR s.provider_id = $2)
  AND s.status = 'available'
  AND s.start_at >= $3
  AND s.start_at < $4
  AND ($5::uuid IS NULL OR EXISTS (
    SELECT 1 FROM provider_services ps
    WHERE ps.provider_id = s.provider_id AND ps.service_id = $5
  ))
ORDER BY s.start_at
LIMIT $6 OFFSET $7
`

type ListAvailableSlotsParams struct {
	TenantID  uuid.UUID `json:"tenant_id"`
	Column2   uuid.UUID `json:"column_2"`
	StartAt   time.Time `json:"start_at"`
	StartAt_2 time.Time `json:"start_at_2"`
	Column5   uuid.UUID `json:"column_5"`
	Limit     int32     `json:"limit"`
	Offset    int32     `json:"offset"`
}

func (q *Queries) ListAvailableSlots(ctx context.Context, arg ListAvailableSlotsParams) ([]AppointmentSlot, error) {
	rows, err := q.db.Query(ctx, listAvailableSlots,
		arg.TenantID,
		arg.Column2,
		arg.StartAt,
		arg.StartAt_2,
		arg.Column5,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AppointmentSlot{}
	for rows.Next() {
		var i AppointmentSlot
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ProviderID,
			&i.StartAt,
			&i.EndAt,
			&i.Status,
			&i.AppointmentID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConversationMessages = `-- name: ListConversationMessages :many
SELECT id, thread_id, direction, message, metadata, created_at
FROM conversation_messages
WHERE thread_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListConversationMessages(ctx context.Context, threadID uuid.UUID) ([]ConversationMessage, error) {
	rows, err := q.db.Query(ctx, listConversationMessages, threadID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ConversationMessage{}
	for rows.Next() {
		var i ConversationMessage
		if err := rows.Scan(
			&i.ID,
			&i.ThreadID,
			&i.Direction,
			&i.Message,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConversationThreads = `-- name: ListConversationThreads :many
SELECT id, tenant_id, customer_id, created_at
FROM conversation_threads
WHERE tenant_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListConversationThreadsParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	Limit    int32     `json:"limit"`
	Offset   int32     `json:"offset"`
}

func (q *Queries) ListConversationThreads(ctx context.Context, arg ListConversationThreadsParams) ([]ConversationThread, error) {
	rows, err := q.db.Query(ctx, listConversationThreads, arg.TenantID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ConversationThread{}
	for rows.Next() {
		var i ConversationThread
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.CustomerID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCustomers = `-- name: ListCustomers :many
SELECT id, tenant_id, first_name, last_name, notes, created_at, updated_at
FROM customers
WHERE tenant_id = $1
  AND ($2::text = '' OR coalesce(first_name, '') ILIKE '%' || $2 || '%' OR coalesce(last_name, '') ILIKE '%' || $2 || '%')
ORDER BY created_at DESC
LIMIT $3 OFFSET $4
`

type ListCustomersParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	Column2  string    `json:"column_2"`
	Limit    int32     `json:"limit"`
	Offset   int32     `json:"offset"`
}

func (q *Queries) ListCustomers(ctx context.Context, arg ListCustomersParams) ([]Customer, error) {
	rows, err := q.db.Query(ctx, listCustomers,
		arg.TenantID,
		arg.Column2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Customer{}
	for rows.Next() {
		var i Customer
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.FirstName,
			&i.LastName,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProviderAvailability = `-- name: ListProviderAvailability :many
SELECT id, provider_id, weekday, start_time, end_time
FROM provider_availability
WHERE provider_id = $1
ORDER BY weekday, start_time
`

func (q *Queries) ListProviderAvailability(ctx context.Context, providerID uuid.UUID) ([]ProviderAvailability, error) {
	rows, err := q.db.Query(ctx, listProviderAvailability, providerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProviderAvailability{}
	for rows.Next() {
		var i ProviderAvailability
		if err := rows.Scan(
			&i.ID,
			&i.ProviderID,
			&i.Weekday,
			&i.StartTime,
			&i.EndTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProviderExceptions = `-- name: ListProviderExceptions :many
SELECT id, provider_id, start_at, end_at, reason, created_at
FROM provider_exceptions
WHERE provider_id = $1
ORDER BY start_at DESC
`

func (q *Queries) ListProviderExceptions(ctx context.Context, providerID uuid.UUID) ([]ProviderException, error) {
	rows, err := q.db.Query(ctx, listProviderExceptions, providerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProviderException{}
	for rows.Next() {
		var i ProviderException
		if err := rows.Scan(
			&i.ID,
			&i.ProviderID,
			&i.StartAt,
			&i.EndAt,
			&i.Reason,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProviderExceptionsBetween = `-- name: ListProviderExceptionsBetween :many
SELECT id, provider_id, start_at, end_at, reason, created_at
FROM provider_exceptions
WHERE provider_id = $1 AND start_at < $3 AND end_at > $2
ORDER BY start_at
`

type ListProviderExceptionsBetweenParams struct {
	ProviderID uuid.UUID `json:"provider_id"`
	EndAt      time.Time `json:"end_at"`
	StartAt    time.Time `json:"start_at"`
}

func (q *Queries) ListProviderExceptionsBetween(ctx context.Context, arg ListProviderExceptionsBetweenParams) ([]ProviderException, error) {
	rows, err := q.db.Query(ctx, listProviderExceptionsBetween, arg.ProviderID, arg.EndAt, arg.StartAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProviderException{}
	for rows.Next() {
		var i ProviderException
		if err := rows.Scan(
			&i.ID,
			&i.ProviderID,
			&i.StartAt,
			&i.EndAt,
			&i.Reason,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProviders = `-- name: ListProviders :many
SELECT id, tenant_id, name, active, created_at, updated_at
FROM providers
WHERE tenant_id = $1
  AND ($2::text = '' OR name ILIKE '%' || $2 || '%')
  AND ($3::boolean IS NULL OR active = $3)
ORDER BY created_at DESC
LIMIT $4 OFFSET $5
`

type ListProvidersParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	Column2  string    `json:"column_2"`
	Column3  bool      `json:"column_3"`
	Limit    int32     `json:"limit"`
	Offset   int32     `json:"offset"`
}

func (q *Queries) ListProviders(ctx context.Context, arg ListProvidersParams) ([]Provider, error) {
	rows, err := q.db.Query(ctx, listProviders,
		arg.TenantID,
		arg.Column2,
		arg.Column3,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Provider{}
	for rows.Next() {
		var i Provider
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listServices = `-- name: ListServices :many
SELECT id, tenant_id, name, duration_minutes, active, created_at, updated_at
FROM services
WHERE tenant_id = $1
  AND ($2::text = '' OR name ILIKE '%' || $2 || '%')
  AND ($3::boolean IS NULL OR active = $3)
ORDER BY created_at DESC
LIMIT $4 OFFSET $5
`

type ListServicesParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	Column2  string    `json:"column_2"`
	Column3  bool      `json:"column_3"`
	Limit    int32     `json:"limit"`
	Offset   int32     `json:"offset"`
}

func (q *Queries) ListServices(ctx context.Context, arg ListServicesParams) ([]Service, error) {
	rows, err := q.db.Query(ctx, listServices,
		arg.TenantID,
		arg.Column2,
		arg.Column3,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Service{}
	for rows.Next() {
		var i Service
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.DurationMinutes,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTenantChannels = `-- name: ListTenantChannels :many
SELECT id, tenant_id, channel_type, external_id, external_key, active, created_at
FROM tenant_channels
WHERE tenant_id = $1
  AND ($2::text = '' OR channel_type = $2)
  AND ($3::boolean IS NULL OR active = $3)
ORDER BY created_at DESC
LIMIT $4 OFFSET $5
`

type ListTenantChannelsParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	Column2  string    `json:"column_2"`
	Column3  bool      `json:"column_3"`
	Limit    int32     `json:"limit"`
	Offset   int32     `json:"offset"`
}

func (q *Queries) ListTenantChannels(ctx context.Context, arg ListTenantChannelsParams) ([]TenantChannel, error) {
	rows, err := q.db.Query(ctx, listTenantChannels,
		arg.TenantID,
		arg.Column2,
		arg.Column3,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TenantChannel{}
	for rows.Next() {
		var i TenantChannel
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ChannelType,
			&i.ExternalID,
			&i.ExternalKey,
			&i.Active,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTenants = `-- name: ListTenants :many
SELECT id, name, timezone, active, greeting_message, created_at, updated_at
FROM tenants
WHERE ($1::text = '' OR name ILIKE '%' || $1 || '%')
  AND ($2::boolean IS NULL OR active = $2)
ORDER BY created_at DESC
LIMIT $3 OFFSET $4
`

type ListTenantsParams struct {
	Column1 string `json:"column_1"`
	Column2 bool   `json:"column_2"`
	Limit   int32  `json:"limit"`
	Offset  int32  `json:"offset"`
}

type ListTenantsRow struct {
	ID              uuid.UUID `json:"id"`
	Name            string    `json:"name"`
	Timezone        string    `json:"timezone"`
	Active          bool      `json:"active"`
	GreetingMessage string    `json:"greeting_message"`
	CreatedAt       time.Time `json:"created_at"`
	UpdatedAt       time.Time `json:"updated_at"`
}

func (q *Queries) ListTenants(ctx context.Context, arg ListTenantsParams) ([]ListTenantsRow, error) {
	rows, err := q.db.Query(ctx, listTenants,
		arg.Column1,
		arg.Column2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTenantsRow{}
	for rows.Next() {
		var i ListTenantsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Timezone,
			&i.Active,
			&i.GreetingMessage,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockCustomerChannel = `-- name: LockCustomerChannel :exec
SELECT pg_advisory_xact_lock(hashtextextended($1::uuid::text || ':' || $2::text, 0))
`

type LockCustomerChannelParams struct {
	TenantChannelID    uuid.UUID `json:"tenant_channel_id"`
	ExternalIdentifier string    `json:"external_identifier"`
}

func (q *Queries) LockCustomerChannel(ctx context.Context, arg LockCustomerChannelParams) error {
	_, err := q.db.Exec(ctx, lockCustomerChannel, arg.TenantChannelID, arg.ExternalIdentifier)
	return err
}

const releaseAppointmentSlot = `-- name: ReleaseAppointmentSlot :one
UPDATE appointment_slots
SET status = 'available', appointment_id = NULL
WHERE id = $1
RETURNING id, tenant_id, provider_id, start_at, end_at, status, appointment_id, created_at
`

func (q *Queries) ReleaseAppointmentSlot(ctx context.Context, id uuid.UUID) (AppointmentSlot, error) {
	row := q.db.QueryRow(ctx, releaseAppointmentSlot, id)
	var i AppointmentSlot
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ProviderID,
		&i.StartAt,
		&i.EndAt,
		&i.Status,
		&i.AppointmentID,
		&i.CreatedAt,
	)
	return i, err
}

const reserveAppointmentSlot = `-- name: ReserveAppointmentSlot :one
UPDATE appointment_slots
SET status = 'reserved', appointment_id = $2
WHERE id = $1
RETURNING id, tenant_id, provider_id, start_at, end_at, status, appointment_id, created_at
`

type ReserveAppointmentSlotParams struct {
	ID            uuid.UUID     `json:"id"`
	AppointmentID uuid.NullUUID `json:"appointment_id"`
}

func (q *Queries) ReserveAppointmentSlot(ctx context.Context, arg ReserveAppointmentSlotParams) (AppointmentSlot, error) {
	row := q.db.QueryRow(ctx, reserveAppointmentSlot, arg.ID, arg.AppointmentID)
	var i AppointmentSlot
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ProviderID,
		&i.StartAt,
		&i.EndAt,
		&i.Status,
		&i.AppointmentID,
		&i.CreatedAt,
	)
	return i, err
}

const updateAppointment = `-- name: UpdateAppointment :one
UPDATE appointments
SET provider_id = $2, service_id = $3, slot_id = $4, start_at = $5, end_at = $6, status = $7, notes = $8, updated_at = now()
WHERE id = $1
RETURNING id, tenant_id, customer_id, provider_id, service_id, slot_id, start_at, end_at, status, notes, created_at, updated_at
`

type UpdateAppointmentParams struct {
	ID         uuid.UUID     `json:"id"`
	ProviderID uuid.UUID     `json:"provider_id"`
	ServiceID  uuid.UUID     `json:"service_id"`
	SlotID     uuid.NullUUID `json:"slot_id"`
	StartAt    time.Time     `json:"start_at"`
	EndAt      time.Time     `json:"end_at"`
	Status     string        `json:"status"`
	Notes      pgtype.Text   `json:"notes"`
}

func (q *Queries) UpdateAppointment(ctx context.Context, arg UpdateAppointmentParams) (Appointment, error) {
	row := q.db.QueryRow(ctx, updateAppointment,
		arg.ID,
		arg.ProviderID,
		arg.ServiceID,
		arg.SlotID,
		arg.StartAt,
		arg.EndAt,
		arg.Status,
		arg.Notes,
	)
	var i Appointment
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CustomerID,
		&i.ProviderID,
		&i.ServiceID,
		&i.SlotID,
		&i.StartAt,
		&i.EndAt,
		&i.Status,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateCustomer = `-- name: UpdateCustomer :one
UPDATE customers
SET first_name = $2, last_name = $3, notes = $4, updated_at = now()
WHERE id = $1
RETURNING id, tenant_id, first_name, last_name, notes, created_at, updated_at
`

type UpdateCustomerParams struct {
	ID        uuid.UUID   `json:"id"`
	FirstName pgtype.Text `json:"first_name"`
	LastName  pgtype.Text `json:"last_name"`
	Notes     pgtype.Text `json:"notes"`
}

func (q *Queries) UpdateCustomer(ctx context.Context, arg UpdateCustomerParams) (Customer, error) {
	row := q.db.QueryRow(ctx, updateCustomer,
		arg.ID,
		arg.FirstName,
		arg.LastName,
		arg.Notes,
	)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.FirstName,
		&i.LastName,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateProvider = `-- name: UpdateProvider :one
UPDATE providers
SET name = $2, updated_at = now()
WHERE id = $1
RETURNING id, tenant_id, name, active, created_at, updated_at
`

type UpdateProviderParams struct {
	ID   uuid.UUID `json:"id"`
	Name string    `json:"name"`
}

func (q *Queries) UpdateProvider(ctx context.Context, arg UpdateProviderParams) (Provider, error) {
	row := q.db.QueryRow(ctx, updateProvider, arg.ID, arg.Name)
	var i Provider
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateService = `-- name: UpdateService :one
UPDATE services
SET name = $2, duration_minutes = $3, updated_at = now()
WHERE id = $1
RETURNING id, tenant_id, name, duration_minutes, active, created_at, updated_at
`

type UpdateServiceParams struct {
	ID              uuid.UUID `json:"id"`
	Name            string    `json:"name"`
	DurationMinutes int32     `json:"duration_minutes"`
}

func (q *Queries) UpdateService(ctx context.Context, arg UpdateServiceParams) (Service, error) {
	row := q.db.QueryRow(ctx, updateService, arg.ID, arg.Name, arg.DurationMinutes)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.DurationMinutes,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTenant = `-- name: UpdateTenant :one
UPDATE tenants
SET name = $2, timezone = $3, greeting_message = COALESCE($4, greeting_message), updated_at = now()
WHERE id = $1
RETURNING id, name, timezone, active, greeting_message, created_at, updated_at
`

type UpdateTenantParams struct {
	ID              uuid.UUID `json:"id"`
	Name            string    `json:"name"`
	Timezone        string    `json:"timezone"`
	GreetingMessage string    `json:"greeting_message"`
}

type UpdateTenantRow struct {
	ID              uuid.UUID `json:"id"`
	Name            string    `json:"name"`
	Timezone        string    `json:"timezone"`
	Active          bool      `json:"active"`
	GreetingMessage string    `json:"greeting_message"`
	CreatedAt       time.Time `json:"created_at"`
	UpdatedAt       time.Time `json:"updated_at"`
}

func (q *Queries) UpdateTenant(ctx context.Context, arg UpdateTenantParams) (UpdateTenantRow, error) {
	row := q.db.QueryRow(ctx, updateTenant,
		arg.ID,
		arg.Name,
		arg.Timezone,
		arg.GreetingMessage,
	)
	var i UpdateTenantRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Timezone,
		&i.Active,
		&i.GreetingMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTenantChannel = `-- name: UpdateTenantChannel :one
UPDATE tenant_channels
SET channel_type = $2, external_id = $3, external_key = $4, active = $5
WHERE id = $1
RETURNING id, tenant_id, channel_type, external_id, external_key, active, created_at
`

type UpdateTenantChannelParams struct {
	ID          uuid.UUID   `json:"id"`
	ChannelType string      `json:"channel_type"`
	ExternalID  string      `json:"external_id"`
	ExternalKey pgtype.Text `json:"external_key"`
	Active      bool        `json:"active"`
}

func (q *Queries) UpdateTenantChannel(ctx context.Context, arg UpdateTenantChannelParams) (TenantChannel, error) {
	row := q.db.QueryRow(ctx, updateTenantChannel,
		arg.ID,
		arg.ChannelType,
		arg.ExternalID,
		arg.ExternalKey,
		arg.Active,
	)
	var i TenantChannel
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ChannelType,
		&i.ExternalID,
		&i.ExternalKey,
		&i.Active,
		&i.CreatedAt,
	)
	return i, err
}

const updateTenantGreeting = `-- name: UpdateTenantGreeting :one
UPDATE tenants
SET greeting_message = $2, updated_at = now()
WHERE id = $1
RETURNING id, name, timezone, active, greeting_message, created_at, updated_at
`

type UpdateTenantGreetingParams struct {
	ID              uuid.UUID `json:"id"`
	GreetingMessage string    `json:"greeting_message"`
}

type UpdateTenantGreetingRow struct {
	ID              uuid.UUID `json:"id"`
	Name            string    `json:"name"`
	Timezone        string    `json:"timezone"`
	Active          bool      `json:"active"`
	GreetingMessage string    `json:"greeting_message"`
	CreatedAt       time.Time `json:"created_at"`
	UpdatedAt       time.Time `json:"updated_at"`
}

func (q *Queries) UpdateTenantGreeting(ctx context.Context, arg UpdateTenantGreetingParams) (UpdateTenantGreetingRow, error) {
	row := q.db.QueryRow(ctx, updateTenantGreeting, arg.ID, arg.GreetingMessage)
	var i UpdateTenantGreetingRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Timezone,
		&i.Active,
		&i.GreetingMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertConversationState = `-- name: UpsertConversationState :one
INSERT INTO conversation_state (tenant_id, customer_id, state, data)
VALUES ($1, $2, $3, $4)
ON CONFLICT (tenant_id, customer_id)
DO UPDATE SET
    state = EXCLUDED.state,
    data = EXCLUDED.data,
    updated_at = NOW()
RETURNING id, tenant_id, customer_id, state, data, updated_at
`

type UpsertConversationStateParams struct {
	TenantID   uuid.UUID `json:"tenant_id"`
	CustomerID uuid.UUID `json:"customer_id"`
	State      string    `json:"state"`
	Data       []byte    `json:"data"`
}

func (q *Queries) UpsertConversationState(ctx context.Context, arg UpsertConversationStateParams) (ConversationState, error) {
	row := q.db.QueryRow(ctx, upsertConversationState,
		arg.TenantID,
		arg.CustomerID,
		arg.State,
		arg.Data,
	)
	var i ConversationState
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CustomerID,
		&i.State,
		&i.Data,
		&i.UpdatedAt,
	)
	return i, err
}
