// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AddUserProvider(ctx context.Context, arg AddUserProviderParams) error
	CancelAppointment(ctx context.Context, id uuid.UUID) (Appointment, error)
	CountAppointments(ctx context.Context, arg CountAppointmentsParams) (int64, error)
	CountCustomers(ctx context.Context, arg CountCustomersParams) (int64, error)
	CountProviders(ctx context.Context, arg CountProvidersParams) (int64, error)
	CountServices(ctx context.Context, arg CountServicesParams) (int64, error)
	CountTenantChannels(ctx context.Context, arg CountTenantChannelsParams) (int64, error)
	CountTenants(ctx context.Context, arg CountTenantsParams) (int64, error)
	CreateAppointment(ctx context.Context, arg CreateAppointmentParams) (Appointment, error)
	CreateAppointmentEvent(ctx context.Context, arg CreateAppointmentEventParams) (AppointmentEvent, error)
	CreateAppointmentSlot(ctx context.Context, arg CreateAppointmentSlotParams) (AppointmentSlot, error)
	CreateConversationMessage(ctx context.Context, arg CreateConversationMessageParams) (ConversationMessage, error)
	CreateConversationThread(ctx context.Context, arg CreateConversationThreadParams) (ConversationThread, error)
	CreateCustomer(ctx context.Context, arg CreateCustomerParams) (Customer, error)
	CreateCustomerChannel(ctx context.Context, arg CreateCustomerChannelParams) (CustomerChannel, error)
	CreateProvider(ctx context.Context, arg CreateProviderParams) (Provider, error)
	CreateProviderAvailability(ctx context.Context, arg CreateProviderAvailabilityParams) (ProviderAvailability, error)
	CreateProviderException(ctx context.Context, arg CreateProviderExceptionParams) (ProviderException, error)
	CreateService(ctx context.Context, arg CreateServiceParams) (Service, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateTenant(ctx context.Context, arg CreateTenantParams) (CreateTenantRow, error)
	CreateTenantChannel(ctx context.Context, arg CreateTenantChannelParams) (TenantChannel, error)
	// users.sql
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateUserWithRole(ctx context.Context, arg CreateUserWithRoleParams) (User, error)
	CreateWebhookLog(ctx context.Context, arg CreateWebhookLogParams) (WebhookLog, error)
	DeactivateProvider(ctx context.Context, id uuid.UUID) (Provider, error)
	DeactivateService(ctx context.Context, id uuid.UUID) (Service, error)
	DeactivateTenant(ctx context.Context, id uuid.UUID) (DeactivateTenantRow, error)
	DeactivateTenantChannel(ctx context.Context, id uuid.UUID) (TenantChannel, error)
	DeleteUser(ctx context.Context, id int32) error
	GetAppointment(ctx context.Context, id uuid.UUID) (Appointment, error)
	GetAppointmentSlotForUpdate(ctx context.Context, id uuid.UUID) (AppointmentSlot, error)
	GetConversationState(ctx context.Context, arg GetConversationStateParams) (ConversationState, error)
	GetConversationThread(ctx context.Context, id uuid.UUID) (ConversationThread, error)
	GetConversationThreadByCustomer(ctx context.Context, arg GetConversationThreadByCustomerParams) (ConversationThread, error)
	GetCustomer(ctx context.Context, id uuid.UUID) (Customer, error)
	GetCustomerByChannel(ctx context.Context, arg GetCustomerByChannelParams) (Customer, error)
	GetProvider(ctx context.Context, id uuid.UUID) (Provider, error)
	GetService(ctx context.Context, id uuid.UUID) (Service, error)
	GetSession(ctx context.Context, id uuid.UUID) (Session, error)
	GetTenant(ctx context.Context, id uuid.UUID) (GetTenantRow, error)
	GetTenantChannel(ctx context.Context, id uuid.UUID) (TenantChannel, error)
	GetTenantChannelByExternalID(ctx context.Context, externalID string) (TenantChannel, error)
	GetUserByIDFull(ctx context.Context, id int32) (User, error)
	GetUserByUsername(ctx context.Context, username string) (GetUserByUsernameRow, error)
	GetUserByUsernameFull(ctx context.Context, username string) (User, error)
	ListAppointments(ctx context.Context, arg ListAppointmentsParams) ([]Appointment, error)
	ListAvailableSlots(ctx context.Context, arg ListAvailableSlotsParams) ([]AppointmentSlot, error)
	ListConversationMessages(ctx context.Context, threadID uuid.UUID) ([]ConversationMessage, error)
	ListConversationThreads(ctx context.Context, arg ListConversationThreadsParams) ([]ConversationThread, error)
	ListCustomers(ctx context.Context, arg ListCustomersParams) ([]Customer, error)
	ListProviderAvailability(ctx context.Context, providerID uuid.UUID) ([]ProviderAvailability, error)
	ListProviderExceptions(ctx context.Context, providerID uuid.UUID) ([]ProviderException, error)
	ListProviderExceptionsBetween(ctx context.Context, arg ListProviderExceptionsBetweenParams) ([]ProviderException, error)
	ListProviders(ctx context.Context, arg ListProvidersParams) ([]Provider, error)
	ListServices(ctx context.Context, arg ListServicesParams) ([]Service, error)
	ListTenantChannels(ctx context.Context, arg ListTenantChannelsParams) ([]TenantChannel, error)
	ListTenants(ctx context.Context, arg ListTenantsParams) ([]ListTenantsRow, error)
	ListUserProviders(ctx context.Context, userID int32) ([]uuid.UUID, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	ReleaseAppointmentSlot(ctx context.Context, id uuid.UUID) (AppointmentSlot, error)
	RemoveUserProvider(ctx context.Context, arg RemoveUserProviderParams) error
	ReserveAppointmentSlot(ctx context.Context, arg ReserveAppointmentSlotParams) (AppointmentSlot, error)
	UpdateAppointment(ctx context.Context, arg UpdateAppointmentParams) (Appointment, error)
	UpdateCustomer(ctx context.Context, arg UpdateCustomerParams) (Customer, error)
	UpdateProvider(ctx context.Context, arg UpdateProviderParams) (Provider, error)
	UpdateService(ctx context.Context, arg UpdateServiceParams) (Service, error)
	UpdateTenant(ctx context.Context, arg UpdateTenantParams) (UpdateTenantRow, error)
	UpdateTenantChannel(ctx context.Context, arg UpdateTenantChannelParams) (TenantChannel, error)
	UpdateTenantGreeting(ctx context.Context, arg UpdateTenantGreetingParams) (UpdateTenantGreetingRow, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) (User, error)
	UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) (User, error)
	UpdateUserTenant(ctx context.Context, arg UpdateUserTenantParams) (User, error)
	UpsertConversationState(ctx context.Context, arg UpsertConversationStateParams) (ConversationState, error)
	// Atomically finds or creates a customer for an inbound channel identifier.
	// This prevents the race condition where two concurrent webhook calls for the
	// same phone number both attempt to create the same customer.
	UpsertCustomerByChannel(ctx context.Context, arg UpsertCustomerByChannelParams) (UpsertCustomerByChannelRow, error)
}

var _ Querier = (*Queries)(nil)
