// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: upsert_customer_by_channel.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const upsertCustomerByChannel = `-- name: UpsertCustomerByChannel :one
WITH ins_customer AS (
    INSERT INTO customers (tenant_id)
    VALUES ($1)
    ON CONFLICT DO NOTHING
    RETURNING id
),
ins_channel AS (
    INSERT INTO customer_channels (customer_id, tenant_channel_id, external_identifier)
    SELECT id, $2, $3
    FROM ins_customer
    ON CONFLICT (tenant_channel_id, external_identifier) DO NOTHING
),
existing AS (
    SELECT cc.customer_id AS id
    FROM customer_channels cc
    WHERE cc.tenant_channel_id = $2
      AND cc.external_identifier = $3
    LIMIT 1
),
new_one AS (
    SELECT id FROM ins_customer
)
SELECT COALESCE(
    (SELECT id FROM existing),
    (SELECT id FROM new_one)
) AS id,
c.tenant_id,
c.first_name,
c.last_name,
c.notes,
c.created_at,
c.updated_at
FROM customers c
WHERE c.id = COALESCE(
    (SELECT id FROM existing),
    (SELECT id FROM new_one)
)
`

type UpsertCustomerByChannelParams struct {
	TenantID           uuid.UUID `json:"tenant_id"`
	TenantChannelID    uuid.UUID `json:"tenant_channel_id"`
	ExternalIdentifier string    `json:"external_identifier"`
}

type UpsertCustomerByChannelRow struct {
	ID        interface{} `json:"id"`
	TenantID  uuid.UUID   `json:"tenant_id"`
	FirstName pgtype.Text `json:"first_name"`
	LastName  pgtype.Text `json:"last_name"`
	Notes     pgtype.Text `json:"notes"`
	CreatedAt time.Time   `json:"created_at"`
	UpdatedAt time.Time   `json:"updated_at"`
}

// Atomically finds or creates a customer for an inbound channel identifier.
// This prevents the race condition where two concurrent webhook calls for the
// same phone number both attempt to create the same customer.
func (q *Queries) UpsertCustomerByChannel(ctx context.Context, arg UpsertCustomerByChannelParams) (UpsertCustomerByChannelRow, error) {
	row := q.db.QueryRow(ctx, upsertCustomerByChannel, arg.TenantID, arg.TenantChannelID, arg.ExternalIdentifier)
	var i UpsertCustomerByChannelRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.FirstName,
		&i.LastName,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
